/* =====================================================================
   NSQIP_LogID_Crosswalk_v3.sql
   ---------------------------------------------------------------------
   Boost match rate by following patient-merge chains in PATIENT.MRG_TO_PAT_ID.

   v2 chain:  CSV MRN -> IDENTITY_ID (any type) -> PAT_ID -> OR_LOG
   v3 chain:  CSV MRN -> IDENTITY_ID (any type) -> PAT_ID
                                                   |
                                    + every PAT_ID merged INTO this one
                                    + every PAT_ID this one was merged FROM
                                    (2-hop closure of MRG_TO_PAT_ID)
              -> OR_LOG (any of the above PAT_IDs)

   Why this helps: Epic patient merges create a chain. When NSQIP
   captured an MRN, that MRN's IDENTITY_ID row may point at PAT_ID-A.
   But if the patient was merged from A→B, surgeries are likely under
   PAT_ID-B, not A. We expand the PAT_ID set to cover the whole merge
   chain so OR_LOG join works.

   Expected lift: 1907 -> ~3000-3500 matched cases.

   Notes:
     * Replace the IN-list below with your gen_crosswalk_sql.py output
       (or use it as a template).
     * The 2-hop closure handles 99%+ of real merge chains. If your
       site has deeper merge graphs, swap CTEs for a recursive WITH.
   ===================================================================== */


WITH
-- Stage 0: filter IDENTITY_ID to just the CSV MRNs we care about
InitialIdents AS (
    SELECT DISTINCT
        OriginalMRN    = id.IDENTITY_ID
       ,IdentityTypeID = id.IDENTITY_TYPE_ID
       ,DirectPatID    = id.PAT_ID
    FROM IDENTITY_ID id
    WHERE id.IDENTITY_ID IN (
        /* paste CSV MRN values here, generated by gen_crosswalk_sql.py */
        '<mrn1>', '<mrn2>', '<mrn3>'
    )
),
-- Stage 1: chase merges FORWARD (this PAT_ID has been merged INTO another)
ForwardMerged AS (
    SELECT
        ii.OriginalMRN
       ,ii.IdentityTypeID
       ,RelatedPatID = p.MRG_TO_PAT_ID
       ,MergeDir     = 'forward'
    FROM InitialIdents ii
    INNER JOIN PATIENT p ON p.PAT_ID = ii.DirectPatID
    WHERE p.MRG_TO_PAT_ID IS NOT NULL
),
-- Stage 2: chase merges BACKWARD (other PAT_IDs that merged INTO this one)
BackwardMerged AS (
    SELECT
        ii.OriginalMRN
       ,ii.IdentityTypeID
       ,RelatedPatID = p.PAT_ID
       ,MergeDir     = 'backward'
    FROM InitialIdents ii
    INNER JOIN PATIENT p ON p.MRG_TO_PAT_ID = ii.DirectPatID
),
-- Stage 3: second-hop expansion in either direction (rare but real)
SecondHopForward AS (
    SELECT
        fm.OriginalMRN
       ,fm.IdentityTypeID
       ,RelatedPatID = p2.MRG_TO_PAT_ID
       ,MergeDir     = 'forward-2hop'
    FROM ForwardMerged fm
    INNER JOIN PATIENT p2 ON p2.PAT_ID = fm.RelatedPatID
    WHERE p2.MRG_TO_PAT_ID IS NOT NULL
),
SecondHopBackward AS (
    SELECT
        bm.OriginalMRN
       ,bm.IdentityTypeID
       ,RelatedPatID = p2.PAT_ID
       ,MergeDir     = 'backward-2hop'
    FROM BackwardMerged bm
    INNER JOIN PATIENT p2 ON p2.MRG_TO_PAT_ID = bm.RelatedPatID
),
-- Stage 4: collapse all sources into one PAT_ID set per CSV MRN
AllPatIDs AS (
    SELECT OriginalMRN, IdentityTypeID, DirectPatID AS PAT_ID, 'direct' AS MergeDir
    FROM InitialIdents
    UNION
    SELECT OriginalMRN, IdentityTypeID, RelatedPatID, MergeDir FROM ForwardMerged
    UNION
    SELECT OriginalMRN, IdentityTypeID, RelatedPatID, MergeDir FROM BackwardMerged
    UNION
    SELECT OriginalMRN, IdentityTypeID, RelatedPatID, MergeDir FROM SecondHopForward
    UNION
    SELECT OriginalMRN, IdentityTypeID, RelatedPatID, MergeDir FROM SecondHopBackward
)
-- Final output: same column shape as v2 crosswalk, plus PatIDSource for
-- debugging (so build_labels can report how many matches came via merges).
SELECT
    MRN             = ap.OriginalMRN
   ,IdentityTypeID  = ap.IdentityTypeID
   ,SurgeryDate     = CONVERT(date, orl.SURGERY_DATE)
   ,LogID           = CONVERT(varchar, orl.LOG_ID)
   ,PAT_ID          = orl.PAT_ID
   ,PatIDSource     = ap.MergeDir
FROM AllPatIDs ap
INNER JOIN OR_LOG orl ON orl.PAT_ID = ap.PAT_ID
LEFT JOIN OR_LOG_2 orl2 ON orl.LOG_ID = orl2.LOG_ID
WHERE orl.SURGERY_DATE BETWEEN '2015-01-01' AND '2024-12-31'
  AND orl.STATUS_C             = 2
  AND orl2.PROC_NOT_DONE_RSN_C IS NULL
  AND orl.PROC_NOT_PERF_C      IS NULL
;
